config/routes.rb
Rails.application.routes.draw do
  root "dashboards#show"
  devise_for :users, controllers: { registrations: "registrations" }

  resources :users, only: [] do
    resource :profile, only: [:show, :new, :create, :edit, :update]
    resources :statuses, only: [:create]
    resources :projects, only: [:create]
  end

  resource :dashboard, only: :show
  resources :pairings, only: :create
  post '/dashboard/send_flow' => "dashboards#send_flow"
end

app/models/dashboard.rb
class Dashboard
  def self.display_feed
    projects = Project.all
    statuses = Status.all
    (projects + statuses).sort_by(&:created_at).reverse.take(5)
  end
end

app/models/pairing.rb
class Pairing < ActiveRecord::Base
  validates_uniqueness_of :user_id, scope: [:pair_id]
  validates :user_id, presence: true, numericality: true
  validates :pair_id, presence: true, numericality: true

  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true, numericality: true
  validates :facebook, format: /\A(http|https)/, allow_blank: true
  validates :twitter, format: /\A(http|https)/, allow_blank: true
  validates :github, format: /\A(http|https)/, allow_blank: true
  validates :linked_in, format: /\A(http|https)/, allow_blank: true
  validates :blog_url, format: /\A(http|https)/, allow_blank: true
  validates :email, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, allow_blank: true

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates :project, presence: true

  def project
    self[:project] || "In deep thought"
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user

  validates :description, inclusion: { in: [ 'Open To Help',
                                             'Ready To Pair',
                                             'In The Zone',
                                             'Sleeping' ] }

  def description
    self[:description] || "Sleeping"
  end
end

app/models/student_registration.rb
class StudentRegistration

  DEFAULT_STATUS = "Sleeping"
  DEFAULT_PROJECT = "In deep thought"

  def initialize(user)
    @user = user
  end

  def create_dependencies
    @user.statuses.create!(description: DEFAULT_STATUS)
    @user.projects.create!(project: DEFAULT_PROJECT)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :statuses
  has_many :projects
  has_many :pairings
  has_one :profile

  def current_status
    statuses.last.description if statuses.exists?
  end

  def current_project
    projects.last.project if projects.exists?
  end

  def paired_with?(user)
    pairings.where(pair_id: user.id).exists?
  end

  def self.ready_to_pair
    users = []
    includes(:statuses).each do |user|
      users << user  if user.current_status == "Ready To Pair"
    end
    users
  end

  def self.open_to_help
    users = []
    all.each do |user|
      if user.current_status == "Open To Help"
        users << user
      end
    end
    users
  end

  def percent_paired_with
    students = User.count - 1
    pairings = self.pairings.count
    total = pairings.to_f / students.to_f
    total.round(2) * 100
  end

  def self.feeling_lucky(current_user)
    
    potential_people = []
    final_people = []

    # need to eliminate these N + 1 queries
    User.all.each do |user|
      if !current_user.paired_with?(user)
        potential_people << user
      end
    end

    potential_people.each do |user|
      if user.current_status == "Ready To Pair"
        final_people << user
      end
    end

    # Need to find a new way to return something if its empty
    if final_people.empty?
      [User.find_or_create_by(email: "notfound@sample.com")]
    else
      [final_people.sample]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :info, :warning, :success

  def authenticate
    if !current_user
      redirect_to new_user_session_path
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate
  respond_to :html, :json, only: :show

  def show
    if params[:query] == "pair"
      @users = User.ready_to_pair
    elsif params[:query] == "help"
      @users = User.open_to_help
    elsif params[:query] == "lucky"
      @users = User.feeling_lucky(current_user)
    else
      @users = User.all.limit(20)
    end
    @users_json = ActiveModel::ArraySerializer.new(@users, root: :users, scope: current_user).to_json

    @feed = Dashboard.display_feed

    respond_to do |format|
      format.html
      format.json { render json: @users_json }
    end
  end

  # Don't know how to properly test this feature, ask for dans help, should also be refactored into it's own rest model
  def send_flow
    flow = Flowdock::Flow.new(api_token: ENV['LP_FLOW'],
        source: "LaunchPairs", from:  { name: current_user.first_name, address: current_user.email })

    flow.push_to_chat(:content => params[:flow][:question], :external_user_name => current_user.first_name)

    flash[:success] = "Your question was sent! Check the flow for any answers"
    redirect_to dashboard_path
  end
end

app/controllers/pairings_controller.rb
class PairingsController < ApplicationController
  respond_to :html, :json

  def create
    @pairing = Pairing.new(user_id: current_user.id, pair_id: params[:pair_id])

    if @pairing.save
      respond_to do |format|
        format.html { redirect_to dashboard_path, info: "Pairing complete!" }
        format.json { render json: @pairing }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: @pairing.errors, status: 422 }
      end
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate

 def show
    @user = User.find(params[:user_id])
    @status = Status.new
    @project = Project.new
    @profile = @user.profile
  end

  def new
    @user = current_user
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    if @profile.save
      flash[:notice] = "Profile information updated."
      redirect_to user_profile_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @profile = Profile.find_by(user_id: params[:user_id])
  end

  def update
    @profile = Profile.find_by(user_id: params[:user_id])
    if @profile.update(profile_params)
      flash[:notice] = "Profile successfully updated"
      redirect_to user_profile_path(current_user)
    else
      render 'edit'
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:blog_url, :facebook, :twitter, :github, :linked_in, :phone_number, :email)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      redirect_to user_profile_path(current_user), 
        success: "Project updated"
    else
      flash[:warning] = "Project can't be blank!"
      redirect_to :back
    end
  end

  private
  def project_params
    params.require(:project).permit(:project)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super do
      if resource.save
        StudentRegistration.new(resource).create_dependencies
      end
    end
  end

  protected

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def create
    @status = Status.new(status_params)
    @status.user = current_user
    @status.save
    redirect_to user_profile_path(current_user), success: "Status updated"
  end

  private

  def status_params
    params.require(:status).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(name)
    content_for(:title) { name }
  end
end

app/views/dashboards/_newsfeed.html.erb
<h2>Newsfeed</h2>
<div class="panel newsfeed">
  <% @feed.each do |event| %>
    <% if event.is_a?(Status) %>
      <p> <span class="user-name"><%= event.user.first_name %></span>
      just updated status to:<span class="update"> <%= event.description %></span> </p>
    <% else %>
      <p><span class="user-name"><%= event.user.first_name %></span>
      just updated project to:<span class="update"> <%= event.project %></span> </p>
    <% end -%>
  <% end -%>
</div>

app/views/dashboards/_question.html.erb
<h2>Quick Question</h2>
<div class="panel quick-question">
  <p>Ask a quick question to your peers for clarification.</p>
  <%= form_for 'flow', url: { controller: :dashboards, action: :send_flow } do |f|  %>
    <%= f.text_area  :question %>
    <%= f.submit "Ask Your Question", class: "button alert", id: "ask-question" %>
  <% end -%>
</div>

app/views/dashboards/show.html.erb
<%= page_title("Dashboard - #{current_user.first_name}") %>
<h1 class="page-title">Dashboard</h1>

<div class="row">
  <div class="large-6 columns">
    <%= render 'dashboards/newsfeed' %>
  </div>

  <div class="large-6 columns">
    <%= render 'dashboards/question' %>
  </div>
</div>

<%= react_component('PairingBox', @users_json) %>

app/views/homes/index.html.erb
<%= page_title('Launch Pairs') %>
<h1>Launch Pairs</h1>

<table>
  <tr>
    <th>Email</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Status</th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td> <%= user.email %></td>
    <td> <%= user.first_name %></td>
    <td> <%= user.last_name %></td>
    <td> <%= user.current_status %></td>
  </tr>
<% end -%>
</table>

app/views/layouts/_flashes.html.erb
<%- flash.each do |key, value| -%>
  <% if key == "notice" %>
    <div data-alert class="alert-box info">
      <%= value %>
       <a href="#" class="close">&times;</a>
    </div>
  <% else %>
    <div data-alert class="alert-box <%= key %>">
      <%= value %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end -%>
<%- end -%>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="row">
    <div class="large-8 columns">
      <ul class="footer-nav">
        <li><a href="#" target="_blank">Submit Issues & Bugs</a></li>
        <li><a href="#" target="_blank">Contribute </a></li>
        <li><a href="#" target="_blank">Request Features</a></li>
      </ul>
    </div>
    <div class="large-4 columns">
      <p id="copyright"> &copy; Copyright <%= Time.now.year %></p>
      <%= image_tag ('la-logo.png'), class: "footer-logo" %>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <a href="/"><div id="logo"></div></a>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to 'Dashboard', dashboard_path %></li>
        <li><%= link_to 'Profile', user_profile_path(current_user) %></li>

        <li class="has-dropdown">
          <a href="#">Account</a>
          <ul class="dropdown">
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
          </ul>
        </li>
      <%- else -%>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if content_for?(:title) %>
    <title><%= yield :title %></title>
  <% else %>
    <title>Launch Pairs</title>
  <% end -%>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/nav' %>

  <div class="row page-wrapper">
    <%= render 'layouts/flashes' %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/profiles/edit.html.erb
<h1>Edit profile information</h1>

<%= form_for [current_user, @profile] do |f| %>
  <%= f.label :blog_url %>
  <%= f.text_field :blog_url %>

  <%= f.label :facebook %>
  <%= f.text_field :facebook %>

  <%= f.label :twitter %>
  <%= f.text_field :twitter %>

  <%= f.label :github %>
  <%= f.text_field :github %>

  <%= f.label :linked_in %>
  <%= f.text_field :linked_in %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit "Update profile" %>
<% end -%>

app/views/profiles/new.html.erb
<h1>Enhance profile with more information:</h1>


<%= form_for @profile, url: user_profile_path(@user, @profile) do |f| %>
  <%= f.label :blog_url %>
  <%= f.text_field :blog_url %>

  <%= f.label :facebook %>
  <%= f.text_field :facebook %>

  <%= f.label :twitter %>
  <%= f.text_field :twitter %>

  <%= f.label :github %>
  <%= f.text_field :github %>

  <%= f.label :linked_in %>
  <%= f.text_field :linked_in %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit "Create profile", class: "button alert small" %>
<% end -%>

app/views/profiles/show.html.erb
<%= page_title("#{@user.first_name}'s Profile") %>
<h1><%= @user.first_name %>'s Profile</h1>

<div class="row">

  <div class="large-4 columns">
     <% if @user == current_user %>
      <% if @profile %>
        <%= link_to "Update Personal Info", edit_user_profile_path(@user), class: "button info" %>
      <% else %>
        <%= link_to "Add Personal Info", new_user_profile_path(@user), class: "button info" %>
      <% end -%>
    <% end -%>
  </div>

  <div class="large-8 columns">
    <h4>Status: <%= @user.current_status %> </h4>
    <h4>Project: <%= @user.current_project %> </h4>
    <h3>Percent Paired With: <%= @user.percent_paired_with %> %</h3>
    <div class="progress small success">
      <span class="meter" style="width: <%= @user.percent_paired_with %>%"></span>
    </div>

    <%= form_for [@user, @status] do |f| %>
      <div class="row">
        <div class="large-12 columns">
          <div class="row collapse">
            <div class="small-10 columns">
              <%= f.select :description, ["Open To Help", "In The Zone", "Ready To Pair"] %>
            </div>

            <div class="small-2 columns">
              <%= f.submit "Update status", class: "button postfix info" %>
            </div>
          </div>
        </div>
      </div>
    <% end -%>

    <%= form_for [@user, @project] do |f| %>
      <div class="row">
        <div class="large-12 columns">
          <div class="row collapse">
            <div class="small-10 columns">
              <%= f.text_field :project %>
            </div>

            <div class="small-2 columns">
              <%= f.submit "Update project", class: "button postfix info" %>
            </div>
          </div>
        </div>
      </div>
    <% end -%>
  </div>
</div>


<div class="row">
  <div class="large-12 columns">
    <% if @profile %>
      <%= @profile.email %>
      <%= @profile.phone_number %>
      <%= link_to 'Facebook', @profile.facebook %>
      <%= link_to 'Twitter', @profile.twitter %>
      <%= link_to 'Github', @profile.github %>
      <%= link_to 'Linked In', @profile.linked_in %>
    <% end -%>
  </div>
</div>